controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

app_login:
    path: /login
    controller: App\Controller\LoginController::index
    methods: [GET, POST]


app_doctor_search_ajax:
    path: /doctor/search_ajax
    controller: App\Controller\DoctorController::searchAjax
    methods: [GET]

app_speciality_search_ajax:
    path: /speciality/search_ajax
    controller: App\Controller\SpecialityController::specialityList
    methods: [GET]

app_location_search_ajax:
    path: /location/list/{page}
    controller: App\Controller\LocationController::locationList
    methods: [GET]
